// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvvnveannfscqxlohjrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dm52ZWFubmZzY3F4bG9oanJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MjM5MTQsImV4cCI6MjA3OTM5OTkxNH0.lvVTK-UGbCsB2C2I6TcJQc--g8uoBftpVBXTNY9IKW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});